### ISSUE TITLE
Helper module for loading basic resources

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#1]
I think a good addition to this package would be a `ressources` module with basic functions for loading textures and programs. This should probably have optional dependencies in the package (mainly Pillow for now).

Maybe something like (On the top of my head right now)

```
load_program
load_texture_1d
load_texture_2d
load_texture_3d
load_texture_cube
load_texture_cube_map
```

**Comment by cprogrammer1994** [comment]
Sounds great. Probably pywavefront and numpy will also be needed

**Comment by einarf** [comment]
> Sounds great. Probably pywavefront and numpy will also be needed

Oh. I guess we can go that far. Maybe also sneak in some [glTF](https://www.khronos.org/gltf/) and other simple formats from [trimesh](https://github.com/mikedh/trimesh)

A lot of this I have in `demosys-py` already and can probably clean up a bit and move over here.

**Comment by einarf** [comment]
Adding this here before it disappears in the every-growing list of TODOs 😄 

Seeing as some people probably still prefer to make their own window I think a resource loading module should be able to be used independently from the windows in this package. If users can provide their own ModernGL context somehow that would be more than possible.

**Comment by einarf** [comment]
Closing because we have a project for this now.
