### ISSUE TITLE
Make PyPI release

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#13]
We should make an initial PyPI release asap.

Remaining:

- [x] Do not hack in debug logging
- [x] Add log level property in `WindowConfig`
- [x] `SceneLoader`s should use the configurable `AttributeNames`

**Comment by einarf** [comment]
Starting on this now and releasing as soon as it's done

**Comment by cprogrammer1994** [comment]
1 more todo:

I want to change the `self._ctx.screen.clear` to `self._ctx.clear` (in this way the entire moderngl_window will be forward comaptible with the [moderngl6 backward comaptible version]

**Comment by einarf** [comment]
Perfect :)

**Comment by cprogrammer1994** [comment]
I will propose a moderngl5 release soon that will add the forward compatibility with moderngl6 wherever it is possible.

The clear will have a color=(r,g,b...) argument instead the current red=, green= ... arguments
since this release is not yet available on PyPI, I have added this clear fix.

**Comment by einarf** [comment]
Any time. There are also a couple of pull requests that have been lingering for a long time.

**Comment by einarf** [comment]
All done here. Will do some testing before PyPI upload.
