### ISSUE TITLE
Look into adding Kivy window

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#16]
Should look into adding a windiw using Kivy. I'm not sure if this will work perfectly cross platform considering OS X only allows 3.3 core. Worth a shot,

**Comment by cprogrammer1994** [comment]
there are some Kivy examples in the moderngl history, they were working fine on windows.

**Comment by einarf** [comment]
Ah right. That is a good reference. I talked to Gabriel Pettier in the Kivy project about this. I'm pretty sure OS X will be a problem, but it could be created as an optional package users can install with pip. `kivy-window` or something. That way we separate the fully cross platform options from the more custom ones.

**Comment by einarf** [comment]
Skipping this for now. Low priority. Can reopen in the future.
