### ISSUE TITLE
VAO wrapper: Add normalized floats

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#24]
We just need to add these as valid types and specify a byte size.

- nf normalized float
- ni2 normalized signed short
- nu4 normalized unsigned int

**Comment by cprogrammer1994** [comment]
there are:

nf = nf4, nf2, nf1 = nu1, nu = nu4, nu2, ni = ni4, ni2, ni1

**Comment by einarf** [comment]
98ff35d4da5fd1cb7a185bd2dc3669f7fcb614db
