### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by stuaxo** [moderngl/moderngl_window#26]
I haven't used this library yet, but wanted to say thanks.

A few years ago tried a whole bunch of GL tutorials in C, C++, Python, JS on desktop, android and the web.

More X-library libs are a really good thing.

In the same way as the buffer protocol made it easy for various libraries to pass around memory areas, maybe at some point in the future there will be low level interface(s) that python graphics libraries will support + interoperate with other effortlessly.

In the meantime, this is a great step forward :)

**Comment by einarf** [comment]
Thank you for the kind words. I definitly support your vision 😄

**Comment by stuaxo** [comment]
Cheers - maybe in about 10 years I'll get round to building it. .. and will leave another comment here ... heh.

**Comment by einarf** [comment]
Hehe. Let's hope so!
