### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#3]
I suggest aligning the version of this package with the ModernGL version. At least the major version. I'm not entirely sure where to go from there, but would that will be sufficient?

**Comment by cprogrammer1994** [comment]
if we align major + minor we must increment patch even if we do a breaking change
I am not sure how to solve this.

**Comment by einarf** [comment]
Not an easy one. We can worry about this later. With proper tagging and branching it should not be a lot of work to bump version numners later if needed.

Think I'll just start at 0.x for now and bump to 1.0.0 when the API seems fairly fixed.

I'll keep this issue open in case someone has more input.

**Comment by yoyonel** [comment]
Hi,
I used a trigger method on GitlabCI (at work) to link 2 projects (a python package and a python application, the scenario look close at your) and "force" building if the "master" (python package) was updated.
It's seems to have the same technology with TravisCI: https://docs.travis-ci.com/user/triggering-builds but i've never try.
Hope this can help your.

**Comment by einarf** [comment]
Looks like moderngl 5 and 6 will work togehter so we don't have to worry too much about this currently
