### ISSUE TITLE
Follow up on Pyglet 2.x

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl_window#4]
Pyglet 2.x might be a good candidate for the default window. Some short exchanges with one of the pyglet devs in reddit indicates they are aiming for 3.3 as a minimum and I urged them to use forward compatible core contexts just in case.

EDIT: They are indeed doing context creation right: https://bitbucket.org/pyglet/pyglet/src/ea6080cbb3c0370124b30543757da8349f8ed3a3/pyglet/gl/cocoa.py?at=default&fileviewer=file-view-default#cocoa.py-196:204

https://www.reddit.com/r/Python/comments/acz876/looking_for_pure_python_graphics_engine_tutorial/edcr2vo/

The advantage of using Pyglet as the standard window is:

* No external dependencies just like PyQt5
* Vastly smaller library compared to PyQt5
* Pyglet is using BSD License while PyQt5 can cause licensing issues for some

**Comment by cprogrammer1994** [comment]
when will they release pyglet 2.x? for now I get 1.3.2 installed.

**Comment by einarf** [comment]
I have no idea when the release is. I'm hanging around on their Discord server now : https://discord.gg/QXyegWe

**Comment by einarf** [comment]
> Benjamin
I have my GL3+ code in a personal fork at the moment, but I plan to merge it in to the main repository as a new branch soon.

**Comment by einarf** [comment]
### More info

```
moderngl.create_context(require=330)
```

result:
```
ValueError: Requested OpenGL version 330, got version 0
```

so obviously a `CGLContextObj` is at least returned something, but the version was not parsed out.

```
moderngl.create_context()
```

Results in:
```
ModernGL: 5.5.0
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GT 650M OpenGL Engine
version: 2.1 NVIDIA-12.0.21 355.11.10.50.10.103
python: 3.7.2 (default, Jan 11 2019, 03:25:25) 
[Clang 10.0.0 (clang-1000.11.45.5)]
platform: darwin
code: 0

...
mgl.Error: GLSL Compiler failed

vertex_shader
=============
ERROR: 0:2: '' :  version '330' is not supported
```

So yep. We are getting a 2.1 context still. This is even with:
```
pyglet.options['shadow_window'] = False
```

**Comment by einarf** [comment]
I figured this out after debugging pyglet. It was the shadow window that caused trouble. I found a way to navigate around that, so pyglet should be working on OS X even with 1.3.x.
