### ISSUE TITLE
Tkinter?

### ISSUE THREAD

**Issue by jonwright** [moderngl/moderngl_window#43]
I have some (rough) code at https://github.com/jonwright/pyopengltk which makes an OpenGL context for tkinter. You can summarise it as creating empty Tk.frame, and then using the window information (winfo_id/winfo_screen) for some ctypes calls. 

Would you be interested to try to get a Tk backend working here?

**Comment by einarf** [comment]
Definitely want to give that a try at least. I'm not entirely sure how to cover mouse, keyboard and window events, but I'm guessing tkinter should be able to provide most of those? Worst case missing events can be emulated somehow.

I guess starting with a simple Tk window with a frame covering the entire window is a good idea. Then later make a widget that can be mixed with other UI elements (making one for PyQt5 and PySide2 as well).

It would probably require a bit of investment in your pyopengltk project. I see `darwin` is missing and I'm sure there will be other things to tweak as well to make this work. If it can benefit both pyopengl and moderngl users.. even better. I'm not sure if you had other things in mind?

One very important thing to resolve is setting a package license on github and in `setup.py` (making license visible on PyPI). I'm not sure what that would be, considering this is derived work from projects using CPOL (pytkogl), zlib (opengl-tcltk) and BSD (pyopengl).

**Comment by jonwright** [comment]
That was fast! I had been thinking to eliminate all the ctypes code and just use the winfo_id and winfo_screen to hook up the window with one of your contexts. It sounds like you already got it working, so I am happy I asked. I don't have access to mac but would be happy to do some testing on windows and linux (although it might take me some time to get up to speed).

**Comment by einarf** [comment]
The tkinter window is located here:
https://github.com/moderngl/moderngl_window/tree/master/moderngl_window/context/tk

You can test the window by running:
```
python.exe .\examples\moderngl_logo.py --window tk
```

.. or any other of the examples.

Currently window resizing, minimize and maximize works. The only way to close the window currently is clicking the window close button. I'll probably see if I can add some more event support later today.

I have access to win10, linux and OS X.

**Comment by einarf** [comment]
@jonwright This might be done pretty fast as an experimental window. See if you can fix the license issue because I don't want to deal with emails about this 😄

**Comment by einarf** [comment]
The way moderngl works in 5.x : `create_context()` relises on an existing opengl context and a default framebuffer. The alternative is `create_standalone_context()` for headless rendering. This is why pyopengltk still would be better off doing the window creation and default framebuffer creation.

We do have an experimental glcontext package : https://github.com/moderngl/glcontext

.. but I'm not sure if the plan is to support context creation and default framebuffer creation in that one. It's a very odd use case.

**Comment by einarf** [comment]
I think the first version of the tk window is actually done now. Currently only tested on windows. I'll test it out tomorrow in linux.

What has been implemented:
- A working `tk.Window` backend (in windows) properly detecting the context and default framebuffer. We also bypass tkinter's event loop.
- Support for hiding mouse cursor
- Support for fullscreen mode
- Support for enable/disable window resize
- Window resize event automatically calculating new viewport
- Key press events
- Key release events
- Key pressed state map
- Unicide character pressed event
- Mouse position events
- Mouse button events
- Mouse button state map
- Mouse drag events (when mouse is moving and any button is pressed)
- Mouse wheel events (positive/negative y)
- .. probably more

Missing features:
- vsync control (Depends on pyopengltk)
- Multisample anti-aliasing support for the default framebuffer (Depends on pyopengltk)

**Comment by einarf** [comment]
Just a more complext test rendering the sponza scene. Ran this for about 15 minutes and the cpu is stable around 5%, gpu also around 5%. Memory also stable at 88.5MB. Looking good.

![Capture](https://user-images.githubusercontent.com/5418180/66515846-207abf80-eae0-11e9-8af9-41ca9ed0cabc.JPG)

**Comment by einarf** [comment]
moderngl-window 1.5.0 is now on PyPI with the new experimental tkinter window.

We'll see how that works out on linux... and possibly OS X in the future.

**Comment by einarf** [comment]
Release moderngl-window `1.5.1` using `pyopengltk==0.0.2` (from `0.0.1`)

I'm not sure what the difference between these versions are, but at least it works. I assume some bug was fixed.

**Comment by einarf** [comment]
Works on Ubuntu Eoan Ermine (AMD Vega) :star: 

![Screenshot from 2019-10-14 14-56-00](https://user-images.githubusercontent.com/5418180/66753144-698d9380-ee93-11e9-9191-927613e3ffa7.png)
 
Missing darwin support. Currently working on that. (Half way done)

**Comment by einarf** [comment]
Most of this is now resolved. We are still missing OS X support in pyopengltk.

More info here : https://github.com/jonwright/pyopengltk/issues/4

**Comment by jonwright** [comment]
Looks good to me. I managed to see some moderngl test windows. Eventually there may be enhancements needed for the context types etc, but those issues are in pyopengltk, I think. You could close this issue I guess?

**Comment by einarf** [comment]
Yup. I guess we can close this. moderngl-window provides a single interface to multiple window libraries so user can just switch the window type when on OS X. (Configuration option or enviroment variable).

**Comment by einarf** [comment]
@jonwright Also, thanks **a lot** for suggesting a window for tikinter. I think a lot of people will be happy.

Adding separate widgets is the next step (existing task #42 ) so users can easily combine these with UI elements.
